sudo: required
services:
  - docker

before_install:
  - docker build -t mpescarmona/docker-kubernetes-react -f Dockerfile.dev .

script:
  - docker run mpescarmona/docker-kubernetes-react npm run test -- --coverage